In [1]:
import numpy as np

In [4]:
seed = 1234
rng = np.random.default_rng(seed)
def f(rng):
    print(rng.random(4))

f(rng)
f(rng)

[0.97669977 0.38019574 0.92324623 0.26169242]
[0.31909706 0.11809123 0.24176629 0.31853393]


In [5]:
def g(seed):
    rng = np.random.default_rng(seed)
    print(rng.random(4))

g(seed)
g(seed)

[0.97669977 0.38019574 0.92324623 0.26169242]
[0.97669977 0.38019574 0.92324623 0.26169242]
